# Generated by Django 4.1.4 on 2023-01-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_publish_data_alter_post_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='about')),
                ('subtitle', models.TextField(max_length=10000)),
                ('aboutme', models.TextField(max_length=10000)),
                ('tw_link', models.URLField()),
                ('tk_in_link', models.URLField()),
                ('github_link', models.URLField()),
            ],
        ),
    ]
