# Generated by Django 4.1.4 on 2023-01-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='aboutme',
            field=models.TextField(max_length=100000000),
        ),
        migrations.AlterField(
            model_name='about',
            name='subtitle',
            field=models.TextField(max_length=100000000),
        ),
    ]
